import { Component } from '@angular/core';
import { INotifications } from 'src/app/shared/interfaces/Notifications';

@Component({
  selector: 'app-notification',
  templateUrl: './notification.component.html',
  styleUrls: ['./notification.component.css'],
})
export class NotificationComponent {
  notifies: INotifications[] = [
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
    {
      id: 0,
      authorName: 'string',
      authorUrl: 'string',
      authorPhoto: 'assets/eeff.png',
      detail: 'string',
      postUrl: 'string',
      postPhoto: 'assets/eeff.png',
    },
  ];

  constructor() {}
}
